SecureApiGateway/secure-api-gateway-ob-uk-rs

- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticscheduledpayments/DomesticScheduledPaymentsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticstandingorders/DomesticStandingOrdersApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalscheduledpayments/InternationalScheduledPaymentsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalstandingorders/InternationalStandingOrdersApi.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/account/v3_0/scheduledpayments/ScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/GlobalExceptionHandler.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/FrequencyService.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/FrequencyType.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/QuarterType.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/scheduledpayment/ScheduledPaymentService.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/standingorder/StandingOrderService.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/validator/IdempotencyValidator.java
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/FrequencyServiceTest.java
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/46
> 46 - Scheduled payments and standing order data for the Accounts API

- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/FRScheduledPaymentDataFactory.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/FRStandingOrderDataFactory.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/LinksHelper.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/FrequencyService.java
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/service/frequency/FrequencyServiceTest.java
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/45
> 45 - v3.1 of Payment API Controllers

- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_1/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_2/internationalstandingorders/InternationalStandingOrdersApiController.java
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/45
> 45 - v3.1.1 to v3.1.3 of Payment API Controllers

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/ingress.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/service.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
issue: https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-uk-rs/issues/27
> create helm chart

- securebanking-openbanking-uk-rs-simulator-sample/Dockerfile
- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose.yml
- securebanking-openbanking-uk-rs-simulator-sample/pom.xml
Switched to spring-boot-maven-plugin, instead of jib, for docker image creation
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/14
> 14 - Switched to spring-boot-maven-plugin

- .github/workflows/pr.yml
- Makefile
Alter the pr action so that a dockerfile with both the tag `latest` and `pr-xxx` are created and pushed to the dev repo.
create a helm chart named `latest` and push to the dev helm bucket.
This brings the pr action inline with the spring config server
> Use defaults for prs

- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/aggregatedpolling/AggregatedPollingApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/eventsubscription/EventSubscriptionApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_4/aggregatedpolling/AggregatedPollingApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/aggregatedpolling/AggregatedPollingApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/eventsubscription/EventSubscriptionApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_3/aggregatedpolling/AggregatedPollingApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_3/eventsubscription/EventSubscriptionsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_4/aggregatedpolling/AggregatedPollingApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_4/eventsubscription/EventSubscriptionsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_5/aggregatedpolling/AggregatedPollingApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_5/eventsubscription/EventSubscriptionsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_6/aggregatedpolling/AggregatedPollingApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_6/eventsubscription/EventSubscriptionsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/service/event/EventPollingService.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/aggregatedpolling/AggregatedPollingApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/eventsubscription/EventSubscriptionApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/service/event/EventPollingServiceTest.java
- Fixed scope for v3.1.4 onwards of Aggregated Polling
- Added Spring Boot integration tests
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/14
> 14 - Add Aggregated Polling and Event Subscriptions endpoints

- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_0/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_1/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_2/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_3/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_4/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_5/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_6/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_0/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_1/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_2/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_3/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_4/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_5/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_6/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_0/FundsConfirmationsApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
Funds confirmation endpoints
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/56
> 56 - Funds confirmation endpoints

- securebanking-openbanking-uk-rs-simulator-sample/docker/Dockerfile
- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose.yml
- securebanking-openbanking-uk-rs-simulator-sample/docker/scripts/wait-for.sh
Ensure config server is ready before starting spring boot application
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/14
> 14 - docker-compose wait for config

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
The current mongo service is `mongodb` not `mongo-mongodb`
> change mongo host to access the current mongo service name

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/account/v3_0/balances/BalancesApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/account/v3_0/offers/OffersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/account/v3_1_3/statements/StatementsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/AccountDataInternalIdFilter.java
- Changes required for the project to build after v3.1.7 model changes
- New controllers for v3.1.7 to follow in a subsequent PR
**Issue**: https://github.com/SecureBankingAccessToolkit/SecureBankingAcceleratorToolkit/issues/73
> 73: v3.1.7 datamodel changes

- _infra/helm/securebanking-openbanking-uk-rs/templates/ingress.yaml
Ingress was redirecting to thw wrong service.
> change backend to the actual service name

- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rs-simulator-sample/docker/docker-compose.yml
**Issue**: https://github.com/SecureBankingAccessToolkit/SecureBankingAcceleratorToolkit/issues/73
> 73: Fixed path to spring cloud config server registry image

- .github/workflows/pr.yml
- .gitignore
Add call to codefresh to fun functional tests.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7
> add functional test call

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
- securebanking-openbanking-uk-rs-simulator-sample/docker/config/securebanking-openbanking-uk-rs-docker.yml
- Delete unused properties spring config
- Added env properties to helm chart
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/95
> 95: specific environment values

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- Added steps actions to deploy the artifact package before build an Image
Issue:https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/106
> 106: improve action when merge and push PR

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/admin/data/DataApiController.java
Update github actions to fix gcloud configuration environment
> Update github actions to fix gcloud configuration environment

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/283
> 283: Fix the wrong CreateDomesticScheduledPayment endpoint in RS Discovery list

- .github/workflows/pr.yml
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/314
> 314: Merge PR github workflow work with caps github username

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Changing some bits for consistency so this values schema matches that
used in the rcs and spring-config helm charts
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/311
> 311: Use settings common across all java apps

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/link/LinksHelper.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_6/domesticpayments/DomesticPaymentsApiControllerTest.java
Issues:
- https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/296
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/313
> 296, 313: Implement Get Details for Domestic Payment and Domestic Scheduled Payment

- README.md
- securebanking-openbanking-uk-rs-simulator-sample/src/main/resources/messages/swagger.properties
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/SwaggerDocumentationConfig.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/resources/messages/swagger.properties
- Updated `SwaggerDocumentationConfig` class to amend api's paths regex in docket
- Updated readme files
- Updated swagger.properties files
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/319
> 319: generate swagger rest api doc

- pom.xml
- securebanking-openbanking-uk-rs-simulator-sample/docker/config/securebanking-openbanking-uk-rs-docker.yml
- securebanking-openbanking-uk-rs-simulator-server/src/test/resources/application-test.yml
- Updated cors library version/
> Updated cors library version

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/PaymentStatusUtils.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/link/LinksHelper.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/411
Description: Added code to implement international scheduled payments payment-details API
> Adding payment-details API implementation

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/DomesticScheduledPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/DomesticStandingOrderConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/FilePaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalScheduledPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalStandingOrderConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculationFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/GenericValidations.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsControllerTest.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/429
> 429: Implement the consent extra validations

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/DomesticPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalScheduledPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/utils/DefaultData.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/utils/ExchangeRate.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/Currencies.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsControllerTest.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/430
> 430: Implementation to calculate the response elements

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/utils/CustomObjectMapper.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/483
> Remove the Min2DecimalPlacesBigDecimalSerializer and BigDecimalDeserializer

- securebanking-openbanking-uk-rs-simulator-sample/docker/Dockerfile
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/508
> 508: Use gcr.io/forgerock-io/java-17:latest base docker image

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/link/LinksHelper.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/471
Adding changes to support international standing orders payment details endpoint
> adding payment details for international standing orders

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_10/vrp/DomesticVrpsApiController.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/577
> 577: Moving v3.1.10 payments controllers to correct package

- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_8/vrp/DomesticVrpsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_9/vrp/DomesticVrpsApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/services/DomesticVrpValidationService.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_8/vrp/DomesticVrpsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_9/vrp/DomesticVrpsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/FilePaymentFileValidationsControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentConsentValidationTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentFileValidationServiceTest.java
Issue: https://github.com/secureapigateway/secureapigateway/issues/643
Description: Added domestic vrp back-office validations.
> 643: Adding domestic vrp validations

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/admin/data/FakeDataApiController.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/490
Added static account id
> Added static account id when generating random data for testing.

- .github/dependabot.yml
Issue: https://github.com/secureapigateway/secureapigateway/issues/889
> 889: Enable dependabot version update PRs

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/slackNotification.yml
- .gitignore
- Makefile
- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Changes to make ready to build a release artifact, java, docker and helm chart
- Bumped parent release 0.9.0
- bumped gateway-ob-uk-common-bom release 0.9.0
- Updated helm chart description
- Updated merge master workflow
- Updated pom file scm section
- Added release caller workflow
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/812
> 812: release action

- Makefile
- secure-api-gateway-ob-uk-rs-server/pom.xml
- Fix makefile to build and publish docker image
- updated server pom file
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release actions docker fix

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/configmap.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- Updated configmap descriptor to rename the configmap to 'application-config', updated references
- Updated deployment descriptor to rename configmap references to 'deployment-config' and 'application-config'
- Updated chart version and name to 'test-facility-bank'
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/851
> Update deployment name, configmap and configmapref

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/secureapigateway/secureapigateway/issues/932
> 932: Update argo application name in github workflows

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
https://github.com/SecureApiGateway/SecureApiGateway/issues/993
> 993: Fixing Mongo secrets to use MONGODV_TEST_FACILITY_ values

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/RsApplicationConfiguration.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountAccessConsentsApiControllerTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1046
> 1046: Configuring Jackson to only serialize non-null fields

- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_10/internationalstandingorders/InternationalStandingOrderConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_5/internationalstandingorders/InternationalStandingOrdersApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteInternationalStandingOrderConsentResponse7Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrderConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_6/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_7/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_8/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/util/link/LinksHelper.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteInternationalStandingOrderConsentResponse7FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrderConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrdersApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteInternationalStandingOrder4Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalStandingOrderConsent6Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteInternationalStandingOrder4ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalStandingOrderConsent6ValidatorTest.java
Implementing International Standing Order Consent API in RS.
Adding validators for International Standing Orders
https://github.com/SecureApiGateway/SecureApiGateway/issues/1064
> 1064: International Standing Order Consent API + Controller

- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBDomesticVRPConsentRequestValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBDomesticVRPConsentRequestValidatorTest.java
Only VRPType: UK.OBIE.VRPType.Sweeping is supported.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1053
> 1053: Implementing validation from VRPTypeVerifier IG script

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v3_0/FundsConfirmationsApiController.java
- Fix funds package refactor done in commons for funds confirmation converters
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1085
> 1085: funds confirmation commons package fix

- Makefile
- pom.xml
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_10/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_2/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_3/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_4/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_5/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_6/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_7/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_8/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_9/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/OBApiReference.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/testsupport/discovery/AvailableApisTestDataFactory.java
- Updated common version
- Fix OBApiReference event aggregated polling method property
- Updated available apis test data factory
- Fix aggregated polling api controllers annotation value
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1125
> 1125: aggregated polling discovery fix

- pom.xml
- Bumped commons bom 2.0.3
- Bumped consent api 2.0.2
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1128
> 1128: prepare release patch 2.0.2

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Add in affinity codeblock but have way of adding affinity codeblock, not required for dev
Issue: https://bugster.forgerock.org/jira/browse/SAPIG-237
> SAPIG-237: Add Affinity codeblock to SAPIG components

- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/BaseOBValidator.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1160
> 1160: Improving log message when BaseOBValidator traps an exception

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rs-backoffice-api/pom.xml
- secure-api-gateway-ob-uk-rs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/pom.xml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-validation/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-core/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
- Updated helm chart, commons and consent-api(RCS) to 2.2.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182
> Prepare release 2.2.0

- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1220
> 1220: Fix workflow for dependabot 

- pom.xml
Updating to the latest SNAPSHOT versions of parent and common dependencies
https://github.com/SecureApiGateway/SecureApiGateway/issues/1223
> 1223: Updating parent and common dependencies

- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/AvailableApiEndpointsResolverTest.java
The test contained in AvailableApiEndpointsResolverTest was disabled due to the mocking not working with the upgrade to Spring Boot 3.
Fixing the test to start the Spring container and use real AvailableEndpoint data
https://github.com/SecureApiGateway/SecureApiGateway/issues/1235
> 1235: Fix AvailableApiEndpointsResolverTest

- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/account/v3_1_10/accounts/AccountsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/account/v3_1_10/transactions/TransactionsApi.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataCreator.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdater.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/FakeDataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiControllerTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataCreatorTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdaterTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/testsupport/HttpHeadersTestDataFactory.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/account/FRAccountData.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/entity/account/FRProduct.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/accounts/transactions/FRTransactionRepository.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/accounts/transactions/FRTransactionRepositoryImpl.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/util/AccountDataInternalIdFilter.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/ControllerEndpointBlacklistHandlerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/factory/OBReadConsentResponseFactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountAccessConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/products/ProductsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/testsupport/api/HttpHeadersTestDataFactory.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/account/consent/OBReadConsent1Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/funds/FundsConfirmationValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/OBValidationServiceTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/account/consent/OBReadConsent1ValidatorTest.java
Accounts data model in common module has been re-generated using a newer version of the code generator, minor updates to code in the RS to be compatible with changes to the data model.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
> 1243: Changes to be compatible with the re-generated accounts data model

- .github/workflows/release.yml
- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Bump versions to 2.3.0

- .github/workflows/release.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Workflow fix for release

- Makefile
- secure-api-gateway-ob-uk-rs-server/pom.xml
Fixes for working with new artifact registry
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Release 2.3.0

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1257
> 1257: Update java action and distribution

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
> 1264: Update actions that have deprecations

- .github/workflows/pr.yml
Add in exclusions for file changes during release
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1263
> 1263: Changes to PR workflows during release

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
Release 2.3.1 for RS
Bump Chart version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1272
> 1272: Create SAPIG version 2.3.1

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Update Helm, Parent, Common and RCS versions to 3.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
> 1404: Create and Release SAPIG Core and OB

- .github/workflows/pr-helm.yml
- Makefile
- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- Bump version to 3.0.1
- Remove phony all as unused
- Correct the value being passed to helm template command
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1460
> 1460: Create and Deploy Release 3.0.1

- .github/workflows/codeql.yml
- .github/workflows/merge.yml
- .github/workflows/pr-helm.yml
- .github/workflows/pr.yml
Enable manual trigger for PR and Merge workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1465
> 1465: Allow Manual run of workflows

- pom.xml
- Parent 3.0.1-SNAPSHOT
- Common 3.0.1-SNAPSHOT
- Consent API 3.0.1-SNAPSHOT
https://github.com/SecureApiGateway/SecureApiGateway/issues/1473
> 1473: Update to latest SAPI-G dependencies

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Update Helm, Common, Parent & RCS version to `3.1.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476
> 1476: Build and Deploy SAPIG 3.1.0 to relenv

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/FakeDataApiController.java
Test account data with multiple balances is required to reproduce the bug in the linked issue. With this change in place, payment tests with a debtorAccount provided by the TPP in the consent will fail until the bug is fixed.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1478
> 1478: Update FakeDataApiController to generate multiple balances

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Add in ob-v* to pr and merge trigger
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1481
> 1481: 1481: Build V4 Images

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Bump Helm, parent, common & RCS version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1516
> 1516: Create release 3.2.0 and deploy

- pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/event/v4_0_0/aggregatedpolling/AggregatedPollingApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/event/v4_0_0/eventsubscription/EventSubscriptionsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v4_0_0/aggregatedpolling/AggregatedPollingApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v4_0_0/eventsubscription/EventSubscriptionsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v4_0_0/aggregatedpolling/AggregatedPollingApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v4_0_0/eventsubscription/EventSubscriptionsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiControllerTest.java
- Adding Controllers and Unit Tests for event notifications flow v4
> LOB-196-event-notifications-flows-v4

- pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/vrp/DomesticVrpConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/vrp/DomesticVrpsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBDomesticVRPConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/OBDomesticVRPRequestValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/consent/OBDomesticVRPConsentRequestValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/consent/OBVRPFundsConfirmationRequestValidator.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1573
Added controller vor Domestic VRPs v4.
> Domestic VRPs v4 components

- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteDomesticScheduledConsentResponse5Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/OBWriteDomesticScheduled2Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/consent/OBWriteDomesticScheduledConsent4Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/OBRisk1ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/OBWriteDomestic2DataInitiationInstructedAmountValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/OBWriteDomestic2ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/payment/consent/OBWriteDomesticScheduledConsent4ValidatorTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1553
Description: Added RS support for the Domestic Scheduled Payments API.
> 1553: Support OBIE Read/Write API v4.0.0

- pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/funds/v4_0_0/FundsConfirmationConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/funds/v4_0_0/FundsConfirmationsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/factory/v3_1_10/OBFundsConfirmationConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/factory/v4_0_0/OBFundsConfirmationConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v3_1_10/FundsConfirmationConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v3_1_10/FundsConfirmationsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v4_0_0/FundsConfirmationConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v4_0_0/FundsConfirmationsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v3_1_10/FundsConfirmationsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v4_0_0/FundsConfirmationConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v4_0_0/FundsConfirmationsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/funds/FundsConfirmationValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/v4/funds/FundsConfirmationValidatorTest.java
LOB-194-funds-confirmation-v4
- Implemented controllers and interfaces to support v4 funds confirmation flow functionality;
- Refactored for the package changes in commons and RCS.
> Funds Confirmation

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataCreator.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataExporter.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdater.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/FakeDataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiControllerTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataCreatorTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataExporterTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdaterTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/account/FRAccountData.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/user/FRUserData.java
Readded new user data for testing accounts flow for v4 from https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/383
> LOB-user-test-data-accounts-flow-v4

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBDomesticVRPConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteDomesticConsentResponse5Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteFileConsentResponse4Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteInternationalConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteInternationalScheduledConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v4_0_0/OBWriteInternationalStandingOrderConsentResponse7Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/file/FilePaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpsApiController.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1614
Description: 
Fixed factories and controllers.
> 1614: Fixing OB v4 issues

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rs-backoffice-api/pom.xml
- secure-api-gateway-ob-uk-rs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/pom.xml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-validation/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-core/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
Bump helm, parent, common and rcs version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625
> 1625: SAPIG Release 4.0.3 - Further OB V4 Support

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/factory/v4_0_0/OBFundsConfirmationConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/domesticstandingorders/DomesticStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/file/FilePaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/internationalpayments/InternationalPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpsApiController.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1614
> 1614: Adding StatusReason array to the payment response objects

- .github/workflows/merge.yml
- .github/workflows/pr-helm.yml
- .github/workflows/pr.yml
- secure-api-gateway-ob-uk-rs-server/docker/Dockerfile
Replace netcap with netcap-traditional in dockerfile
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1662
> 1622: Fix installing Netcat in docker imager

- .github/workflows/merge.yml
- .github/workflows/pr-helm.yml
- .github/workflows/pr.yml
- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- Remove unwanted file changes for path ignore
- _Revert parent to 4.0.4 as no changes in 4.0.5_ - Now need to bump to 4.0.5 for licencing changes
- Bump helm version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1664
> 1664: Prepare SAPIG 4.0.5

- _infra/helm/securebanking-openbanking-uk-rs/readme.md
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
Update configmap name
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1675
> 1675: Tidy OB Kustomize manifests

- _infra/helm/securebanking-openbanking-uk-rs/readme.md
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
Rename ob-deployment-config & ob-secrets to rs-sapig
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676
> 1676: Split IG into AS/RS and deploy to Devenvs

- pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/vrp/DomesticVrpConsentsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/OBApiReference.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/service/migration/ConsentComparisonService.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v4_0_0/vrp/DomesticVrpConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/service/migration/ConsentComparisonServiceTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1644
> 1644: Adding PUT support

- pom.xml
Update parent, common and RCS to `5.0.1-SNAPSHOT`
Issue: https://github.com/SecureApiGateway/secure-api-gateway-ci/pull/180
> 1711: Post SAPIG 5.0.0 Clean Up
