SecureApiGateway/secure-api-gateway-ob-uk-rs

- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticstandingorders/DomesticStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalpayments/InternationalPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalstandingorders/InternationalStandingOrdersApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_6/domesticpayments/DomesticPaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRDomesticPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRDomesticScheduledPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRDomesticStandingOrderPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRFilePaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRInternationalPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRInternationalScheduledPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/FRInternationalStandingOrderPaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/payment/PaymentSubmission.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/IdempotentRepositoryAdapter.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/DomesticScheduledPaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/DomesticStandingOrderPaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/FilePaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/InternationalPaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/InternationalScheduledPaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/InternationalStandingOrderPaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/payments/PaymentSubmissionRepository.java
- securebanking-openbanking-uk-rs-simulator/src/main/resources/application.yml
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticpayments/DomesticPaymentsApiControllerTest.java
Rather than saving a payment submission with its primary key set to the consent's ID, this change ensures each submission has its own unique ID. This means that the `IdempotentRepositoryAdapter` needs to find any existing payment submissions for the consent in question by the consent's ID, rather than the submission's ID.
There are quite a few minor changes to several classes in this PR, but the pertinent changes were made to these classes:
- `PaymentSubmissionRepository` (new repository interface with the required `findByConsentId` method).
- `PaymentSubmission` (each Submission knows how to return its consentId).
- `IdempotentRepositoryAdapter` (using `findByConsentId`).
- `DomesticPaymentsApiControllerTest` (new test methods concerning the above).
Issue: …
> 45 - Find any existing Payment Submissions for the same Consent

- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_0/CallbackUrlsApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/callbackurl/CallbackUrlsApi.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_0/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_1/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/callbackurl/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_3/callbackurl/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_4/callbackurl/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_5/callbackurl/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_6/callbackurl/CallbackUrlsApiController.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/EventApiResponseUtil.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/event/FRCallbackUrl.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/event/FREventNotification.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/document/event/FREventSubscription.java
- securebanking-openbanking-uk-rs-simulator/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/validator/EventApiValidator.java
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/event/v3_1_2/callbackurl/CallbackUrlsApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
- Tidied up controllers (e.g. constructor injection, removed annotations that are specified in the API interfaces)
- Removed TPP lookup related code
- Re-wrote `EventApiResponseUtil` () - using `getVersionFromPath()` instead of requiring OBVersion to be provided to its constructor (makes extending previous versions of controllers easier and less error prone).
- Made error handling consistent - throwing `OBErrorResponseException` in all versions
- Added Spring Integration tests
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/51
> 51 - Callback URLs API controllers

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/AvailableApiEndpoint.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/AvailableApiEndpointsResolver.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/ControllerEndpointBlacklistHandler.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/ControllerMethod.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryApiConfigurationProperties.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryApiService.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/SwaggerDocumentationConfig.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/web/DisabledEndpointInterceptor.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/AvailableApiEndpointsResolverTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/ControllerEndpointBlacklistHandlerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryApiServiceTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/discovery/AvailableApisTestDataFactory.java
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/5
> 5 - Fix for Discovery endpoint definition to appear in the swagger spec

- securebanking-openbanking-uk-rs-simulator-server/pom.xml
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/admin/data/DataUpdater.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/admin/data/FakeDataApiController.java
Compilation fix due to `FRAccount` ambiguity
- Required after a new `FRAccount` object was added to `securebanking-openbanking-uk-forgerock-datamodel` (for data transfer rather than storage)
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
> 58 - Remove FRAccount complilation ambiguity

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApiControllerTest.java
Removed `FRBankAccount` and renamed `FRBankAccountWithBalance` to `FRAccountWithBalance`
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
> 58 - Removed FRBankAccount and renamed FRAccountWithBalance

- .github/workflows/merge-master.yml
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
There was an issue with the kubernetes deployment. some config was mismatching.
The merge GH actions was not tagging charts correctly, this has been fixed.
Delegate WAF config to external config for ease of development.
> fix issues with k8s deployment

- _infra/helm/securebanking-openbanking-uk-rs/templates/ingress.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Give the ingress a configurable domain and subdomain. default tls to wildcard.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/issues/40
> add configurable ingress

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Allow for a configurable mongo host. default to suffix the namespace `mongo-dev`.
Change the default sslcert for consistency across all securebanking applications `sslcert`
> fix mongo and sslconfig

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Deploying the mongodb chart into a different namespace will suffix the service with that namespace for argo deployments.
apply logic to add the suffix for a given namespace if the deployment is argo controlled.
> add mongodb namespace config

- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Remove the backend protocol from the rs ingress. it does not need to be https, we use this ingress only for ease of development. The ingress itself would not be in a production environment as all traffic is routed through IG.
> remove https nginx annotation

- .github/workflows/merge-master.yml
- .github/workflows/pr.yml
Change pr to only use the `pr-<prNumber>` tag and move the latest tag to the merge action.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/issues/54
> make latest tag on merge only

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- securebanking-openbanking-uk-rs-simulator-sample/docker/config/securebanking-openbanking-uk-rs-docker.yml
- securebanking-openbanking-uk-rs-simulator-sample/src/test/resources/application-test.yml
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/AvailableApiEndpointsResolver.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryApiService.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/WebMvcConfig.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/AvailableApiEndpointsResolverTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryApiServiceTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/link/LinksHelperTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/resources/application-test.yml
Ensure URLs returned from the RS simulator are derived from the X-Forwarded headers. Specifically URLs from:
* The Discovery endpoint (`/open-banking/discovery`)
* The Swagger documentation endpoint (`/api-docs`)
* Self links to resources from the Payments, Events or Fund Confirmation URLs (excluding the Accounts API which uses the `x-ob-url` header).
**N.B.** If X-Forwarded headers are not provided then the RS simulator defaults to `http://localhost:8080`.
**Issue**: https://github.com/SecureBankingAccessToolkit/SecureBankingAcceleratorToolkit/issues/76
> 76: Derive base URL from X-Forwarded headers

- _infra/helm/securebanking-openbanking-uk-rs/templates/service.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
- securebanking-openbanking-uk-rs-simulator-sample/pom.xml
- securebanking-openbanking-uk-rs-simulator-sample/src/main/resources/application.yml
Add `app` label to the Service Manifest for matching with the prometheus ServiceMonitor manifest.
Add the micrometer dependency to the sample service and add prometeus to the exposed actuator endpoints.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/issues/57
> add Prometheus support

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Add a tagDelimiter to allow selecting an image by digest rather than tag name.
This is required for the `dev` environment which is updated via the `latest`digest.
remove the argo controlled mongodb and simply add host.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/21
> add mongodb host and tagDelimiter

- .github/workflows/merge-master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Add github sha to docker image on merge to master.
add github tag to docker image and push to release repo when a release is made
remove all release repo references from merge/pr actions.
Publishing a helm chart is not required at the merge or pr phase.
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
> add docker tags for different action steps

- .gitignore
- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/util/link/LinksHelper.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/297
- The existing API /backoffice/payment-funds-confirmation was changed to use as a response body the class OBWriteFundsConfirmationResponse1.
- The unit tests were updated.
> 297: Modify the funds confirmation route

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/ingress.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
Huge amount of CPU being requested at start up caused node issue and
eviction of pods.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/311
> 311: Add resource limits to container

- _infra/helm/securebanking-openbanking-uk-rs/templates/ingress.yaml
Change pathType to prefix to fix nginx 404 not found error for https://obdemo.dev.forgerock.financial/ig(/%7C$)(.*)
> Fix ingress 404 error

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java
The Get Details Endpoints are missing from RS Discovery.
- https://obdemo.ENV.forgerock.financial/rs/open-banking/v3.1.8/pisp/domestic-scheduled-payments/{DomesticScheduledPaymentId}/payment-details
- https://obdemo.ENV.forgerock.financial/rs/open-banking/v3.1.8/pisp/domestic-payments/{DomesticPaymentId}/payment-details
> Add Payment Details Uris in RS Discovery

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElements.java
- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApi.java
- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/swagger/SwaggerApiTags.java
- securebanking-openbanking-uk-rs-simulator-server/pom.xml
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/DomesticPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculationFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/PaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/PaymentConsentValidationFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/RsApplicationConfiguration.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/exceptions/GlobalExceptionHandler.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/TestConfiguration.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
- Wrote Unit tests for the new controller with base tests for domestic payment consent requests
- Created the REST API
- Created the pattern for validation
- Created the pattern for calculation
- Added RS Configuration to configure the rest template and jackson mapper
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/428
> 428: Backoffice API to calculate payment consent response elements

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElements.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/DomesticPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/GenericValidations.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/PaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/Currencies.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsControllerTest.java
- Implement pattern to manage the error list for validations
- Improvements in controller to avoid throw internal exceptions when error event happens
- Completion of domestic payments consent request validation test coverage
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/432
> 432: Handling error events for validations

- securebanking-openbanking-uk-rs-obie-api/pom.xml
Currently, the codegen produces output which includes an unused import for JsonNullable. This causes issues as this class is not on the classpath and therefore causes compilation errors.
Disabling support for JsonNullable as we don't use this functionality and it seems unlikely that we would want to in the future.
This change has been applied to the common module which contains the datamodel, the change to this project will produce the APIs which will be compatible. See: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk/pull/47
Issue: SecureBankingAccessToolkit/SecureBankingAccessToolkit#450
> 450: Preventing the codegen from using JsonNullable

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElements.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalScheduledPaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/InternationalStandingOrderConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/calculation/PaymentConsentResponseCalculationFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/utils/CustomObjectMapper.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/utils/DefaultData.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/DomesticStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/GenericValidations.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalScheduledPaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/InternationalStandingOrdersConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/PaymentConsentValidation.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/PaymentConsentValidationFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/RsApplicationConfiguration.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/CalculateResponseElementsControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticscheduledpayments/DomesticScheduledPaymentsApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/domesticstandingorders/DomesticStandingOrdersApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalscheduledpayments/InternationalScheduledPaymentsApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_0/internationalstandingorders/InternationalStandingOrdersApiControllerTest.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/442
All the errors are using the following Error model:
```json
{
"Code": "string",
"Errors": [
{
"ErrorCode": "string",
"Message": "string",
"Path": "string"
}
]
}
```
In the RS project for calculate elements APIs we have two types of verification on the request body.
1. The verification of all the required fields and their format/value (the Instructed Amount) for the all the types of Domestic Payments. Returning a DATA_INVALID_REQUEST error type with a custom message if the criteria aren't met.
2. The verification of all the required fields and their format/value (the Instructed Amount, the Exchange Rate Information) for the all the types of International Payments, depending of the rate type (Actual, …
> 442: Implement handling exceptions to reject the consent

- securebanking-forgerock-rs-platform-client/src/main/java/com/forgerock/securebanking/rs/platform/client/services/CloudPlatformClientService.java
- securebanking-forgerock-rs-platform-client/src/test/java/com/forgerock/securebanking/rs/platform/client/services/PlatformClientServiceTest.java
- securebanking-forgerock-rs-platform-client/src/test/java/com/forgerock/securebanking/rs/platform/client/test/support/DomesticPaymentConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/ControllerEndpointBlacklistHandlerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_4/domesticpayments/DomesticPaymentsApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiControllerTest.java
- Consent API expects OBIntentObject field in response object from IDM (via IG)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/522
> 522: Updating RS consent API to work with the new IDM consent structure

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/domesticpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/domesticscheduledpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/domesticstandingorders/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/filepayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/internationalpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/internationalscheduledpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/internationalstandingorders/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/domesticpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/domesticscheduledpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/domesticstandingorders/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/filepayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/internationalpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/internationalscheduledpayments/CalculateResponseElementsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_5/internationalstandingorders/CalculateResponseElementsController.java
- Set the status in OB response object for all payment consents instead to set the hardcoded status in IG
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/573
Comment: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/573#issuecomment-1277623393
> 573: calculate file payment elements fix consent status

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_3/file/FilePaymentsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/file/FilePaymentsApiController.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/617
Fixed missing status in the File Payments controller.
> Added status to the response

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Fix for codefresh changes for allowing github actions to call pipelines
Issue : https://github.com/SecureApiGateway/SecureApiGateway/issues/706
> 706 Fix github actions calling codefresh pipelines

- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/FilePaymentFileValidationsControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentConsentValidationTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/validation/FilePaymentFileValidationServiceTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/716
Fixed datamodel method references to use proper definitions and parameters for method calls.
> Fixing unit test to use latest methods from datamodel dependency.

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/v3_1_4/filepayments/FilePaymentFileValidationsController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/accounts/accounts/FRAccountRepository.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/accounts/accounts/FRAccountRepositoryCustom.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/accounts/accounts/FRAccountRepositoryImpl.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/persistence/repository/accounts/balances/FRBalanceRepository.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/account/AccountsApiControllerTest.java
- Added method to retrieve the account identifier by identifiers
- user id (`optional`), name, identification and schema name to validate the trusted beneficiary and update the debtor account provided in the consent with the account id if necessary (ex. VRP payments sweeping case)
Issue: https://github.com/secureapigateway/secureapigateway/issues/637
> 637: vrp consent decision accountId

- securebanking-openbanking-uk-rs-backoffice-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApi.java
- securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_0/FundsConfirmationsApi.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/backoffice/payment/PaymentFundsConfirmationApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_0/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/funds/v3_1_3/FundsConfirmationsApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/testsupport/api/HttpHeadersTestDataFactory.java
Issue: https://github.com/secureapigateway/secureapigateway/issues/715
> 715: X-fapi-financial-id header should be optional

- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/admin/data/FakeDataApiController.java
- securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/configuration/TestUserAccountIds.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rs/api/admin/data/FakeDataApiControllerTest.java
- securebanking-openbanking-uk-rs-simulator-server/src/test/resources/application-test.yml
New configuration allows test AccountIds to be configured for usernames. When FakeDataApiController generates test data for a user, it will check if there are preconfigured AccountIds and use these in order they appear in the config file.
The configuration is optional. It may be completely omitted, or have no configuration for a particular username. In this case the AccountIds are generated randomly. For usernames with configuration, random AccountIds will also be produced when the configured list of ids is exhausted.
Making this change allows us to have random test data with predictable AccountIds, which makes testing easier by allowing us to specify known AccountIds in requests which require a DebtorAccount to be supplied.
Issue: …
> 795: Adding testdata spring config which supports configuring the AccountIds generated by the FakeDataApiController

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- securebanking-forgerock-rs-platform-client/src/main/java/com/forgerock/securebanking/rs/platform/client/configuration/ConsentRepoConfiguration.java
- securebanking-forgerock-rs-platform-client/src/main/java/com/forgerock/securebanking/rs/platform/client/services/CloudPlatformClientService.java
- securebanking-forgerock-rs-platform-client/src/test/java/com/forgerock/securebanking/rs/platform/client/configuration/ConsentRepoConfigurationTest.java
- securebanking-forgerock-rs-platform-client/src/test/java/com/forgerock/securebanking/rs/platform/client/services/PlatformClientServiceTest.java
- securebanking-forgerock-rs-platform-client/src/test/resources/application-test.yml
The IG Consent Repo (/repo route), is an internal feature. Use the internal IG address to access it, so that the ingress rule can be removed.
Note: In future the /repo route will be removed in favour of a dedicated consent API
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/239
> 239: Call IG internal svc address to access consent repo

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
- pom.xml
- secure-api-gateway-ob-uk-rs-server/docker/config/securebanking-openbanking-uk-rs-docker.yml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/RSServerApplication.java
- secure-api-gateway-ob-uk-rs-server/src/test/resources/application-test.yml
There is no requirement to support CORS for the RS, the RS is never expected to be called from a browser.
Removing the dependency and related configuration
https://github.com/SecureApiGateway/SecureApiGateway/issues/880
> 880: Removing securebanking-common-cors dependency and configuration

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
Removing dependency on spring config server and its configuration.
Merging config from: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-spring-config/blob/master/docker/securebanking-openbanking-uk-rs.yml into secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/881
> 881: Moving spring config from the config server repo into the app

- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
The mandatory config is the most important config that the customer needs to be aware of, moving it to the top of the file so that it can be found more easily.
Removing spring.application.name configuration as it is not used.
https://github.com/SecureApiGateway/SecureApiGateway/issues/749
> 749: Moving mandatory spring config template to the top of the file

- secure-api-gateway-ob-uk-rs-backoffice-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/backoffice/api/payment/PaymentFundsConfirmationApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/PaymentFundsConfirmationApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/PaymentFundsConfirmationApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/testsupport/api/HttpHeadersTestDataFactory.java
The existing implementation for the self links is broken as it includes the /backoffice API in the path, it is also missing the /rs/ path element.
All funds confirmation requests get mapped on to the single PaymentFundsConfirmationApiController (that is part of the /backoffice API). In order to build the self links this controller needs to know that original OB URL that was used to call IG.
Adding `x-ob-url` header parameter to the controller and using it to build the self links. This is the same pattern used by the Accounts API.
https://github.com/SecureApiGateway/SecureApiGateway/issues/874
> 874: Fixing self links for PaymentFundsConfirmationApiController

- _infra/helm/securebanking-openbanking-uk-rs/templates/configmap.yaml
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rs/values.yaml
- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rs-server/src/test/resources/application-test.yml
Deployment specific Spring configuration can be provided by adding the properties as yaml to the `springConfig` object in the helm values file. By default this object will be empty.
If Spring Config is provided in this manner, then a ConfigMap is created which contains the configuration block. This is then mounted into the RS docker container under /app/config/application.yml. Spring property resolution will check for config in this file before it falls back to the application.yml found within the JAR.
Removed FR deployment specific `testdata` configuration from application.yml (moved it into applicaiton-test.yml as unit tests use it); for dev deployments this will be supplied via ArgoCD. See PR: https://github.com/SecureApiGateway/sbat-cd/pull/101 …
> 888: Allowing Spring config to be overridden by helm values

- .github/workflows/release.yml
- Makefile
The java artifact needs to be published before docker and helm chart to resolve properly the dependencies
- Updated make file
- Updated release caller workflow
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release action docker workflow fix

- .github/dependabot.yml
Issue: https://github.com/secureapigateway/secureapigateway/issues/889
> 889: Correct path for docker dependabot updates

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Preparing for v1.0.0 release.
- Update helm chart version
- update dependency versions of parent and bom
Issue: https://github.com/secureapigateway/secureapigateway/issues/927
> 927: Update dependency and chart version for 1.0.0

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- Updated pr workflow to pass the variable 'ARGO_VALUES_PREFIX=testFacilityBank'
- Updated merge master workflow to pass the variable 'ARGO_VALUES_PREFIX=testFacilityBank'
Issue: https://github.com/secureapigateway/secureapigateway/issues/934
> 934 fix argocd application values prefix on PR pushes to an environment

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- Updated chart 1.0.0 to 1.0.1
- Prepare to build the release 1.0.1 Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/969
> 969: Update chart version to prepare release 1.0.1

- pom.xml
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/services/validation/DomesticVrpValidationService.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/services/validation/DomesticVrpValidationServiceTest.java
The bug was enforcing that the payment InstructedAmount matched the MaximumIndividualAmount control param.
Fixed to validate that InstructedAmount <= MaximumIndividualAmount.
Added unit tests and improved error message for currency validation.
Updated uk.bom.version to 1.0.3-SNAPSHOT to pickup new error code.
https://github.com/SecureApiGateway/SecureApiGateway/issues/983
> 983: Fixing bug in DomesticVrpValidationService preventing VRPs from being submitted due to incorrect MaxIndividualAmount validation being applied

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/calculation/InternationalPaymentConsentResponseCalculation.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/calculation/InternationalScheduledPaymentConsentResponseCalculation.java
ExchangeRateInformation field is optional, if it is not supplied then the bank will generate an ExchangeRateInformation in the response.
The generated data will use an Indicative RateType and use the consent's InstructedAmount.currency as the UnitCurrency.
Note: we are not making any changes to the consent request object, so will not be reintroducing the bug which caused payment validation to fail due to initiation data mismatch (fixed in PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/172). 
Functional tests have been improved to verify the behaviour, see this PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-functional-tests/pull/125
https://github.com/SecureApiGateway/SecureApiGateway/issues/980
> 980: Generating an Indicative FX rate for InternationalPaymentConsents which omit the ExchangeRateInformation

- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/CalculateResponseElementsControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/vrp/DomesticVrpsApiControllerTest.java
Adding spring-boot-starter-validation dependency to rs-server pom. This change enables Java Bean validation, this means that all validation constraints defined in the OBIE schema will automatically be applied to request objects.
Fixing CalculateResponseElementsControllerTest assertions to validate error responses caused by bean validation.
Adding test to VRP controller to verify that bean validation is enabled by submitting an empty request body and checking that the error response indicates which fields need to be supplied.
https://github.com/SecureApiGateway/SecureApiGateway/issues/578
> 578: Enabling Java Bean validation

- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/CloudClientModuleConfiguration.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/CloudPlatformClientService.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/RSServerApplication.java
CloudClientModuleConfiguration controls the package scan for the cloud-client module, restricting it only to the subpackages in the java module.
Updated RSServerApplication to remove the broad scan and rely on the default scan done by `@SpringBootApplication` annotation, which uses the annotated class's package as the base package.
Added an `@Import` for the cloud client module to RSServerApplication so that the new module gets loaded.
https://github.com/SecureApiGateway/SecureApiGateway/issues/991
> 991: Creating Spring Boot module for java module secure-api-gateway-ob-uk-rs-cloud-client

- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
The database name is currently mongo, which is confusing. Renaming it to test-facility-bank.
This will also make it easier to determine the purpose of the database if we have multiple databases running in the same MongoDB instance (Consent Store for example).
Auth credentials can now be created for use by the test-facility-bank service to connect to this database.
https://github.com/SecureApiGateway/SecureApiGateway/issues/993
> 993: Renaming the MongoDB database used by the test-facility-bank

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- DataAPI-payload-definition.md
As we provide an Admin API (DataAPI) to be consumed by the customer to push their user bank accounts data, we need to provide also the version of the payload expected by Admin API. Having this md file in this repository it can be released and therefore versioned. It will be refer from the wiki page https://github.com/SecureApiGateway/SecureApiGateway/wiki/How-to-create-test-facility-bank-users-and-data
- Added `DataAPI-payload-definition.md` file to provide the payload definitions that can be releases by version
- Updated github workflows to ignore the new md file
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/952
> 952: added admin API payload definition readme file

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
Configuring the properties via environment variables supplied from a secret. The properties configure the database, username and password to use in the MongoDB connection string.
Note: we have a convention of using the same database name and username, hence both env vars using the same key.
https://github.com/SecureApiGateway/SecureApiGateway/issues/993
> 993: Configuring Spring Data MongoDB properties

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/validation/PaymentConsentValidation.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/payment/CalculateResponseElementsControllerTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/986 
Description:
- removed the required condition for the "AGREED" rateType case since it was a wrong validation
According to the OB spec:
- For an "Agreed" RateType a requested exchange rate is populated in the ExchangeRate field, against the UnitCurrency. I.e, if the UnitCurrency is GBP and CurrencyOfTransfer is USD, then ExchangeRate will be 1.34 (USD to 1 GBP).
- For an "Agreed" RateType the exchange rate contract identifier is populated in the ContractIdentification field.
- A PISP must not specify ExchangeRate and/or ContractIdentification when requesting an Actual RateType.
- A PISP must not specify ExchangeRate and/or ContractIdentification when requesting an Indicative RateType.
See [international payment …
> 986: International Payments & International Scheduled Payments wrong unitCurrency validation

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- Updated helm charts version to 1.0.3
- Bumped common version 1.0.5
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1040
> 1040: prepare versions to build release 1.0.3

- secure-api-gateway-ob-uk-rs-server/pom.xml
Executable jar will be: secure-api-gateway-ob-uk-rs-server-$VERSION-exec.jar
Updated docker plugin to the use exec jar
The jar with no classifier will be a standard jar, which can be used as a library in extension projects.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1067
> 1067: Configuring spring-boot-maven-plugin to repackage the jar with an "exec" classifier

- Makefile
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_5/domesticscheduledpayments/DomesticScheduledPaymentsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteDomesticScheduledConsentResponse5Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_6/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_6/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_7/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_7/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_8/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_8/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/domesticpayments/DomesticPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/domesticscheduledpayments/DomesticScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/util/link/LinksHelper.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteDomesticScheduledConsentResponse5FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteDomestic2DataInitiationInstructedAmountValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteDomesticScheduled2Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticScheduledConsent4Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteDomestic2DataInitiationInstructedAmountValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticScheduledConsent4ValidatorTest.java
Using the RCS Consent Store for Domestic Scheduled Payment Consents.
Adding DomesticScheduledPaymentConsentsApi + Controller
Updating DomesticScheduledPaymentsApiController to fetch consents from the RCS Consent Store.
> 1060: Domestic Scheduled Payment Consent API

- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApi.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteInternationalScheduledConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_6/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_7/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_8/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/util/link/LinksHelper.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/OBWriteInternationalScheduledConsentResponse6FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteInternationalScheduled3Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalScheduledConsent5Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBWriteInternationalScheduled3ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalScheduledConsent5ValidatorTest.java
Implementing International Scheduled Payment Consent API in RS.
Adding validators for Payment Consents.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1063
> 1063: Adding InternationalScheduledPaymentConsentsApi + Controller

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/OBApiReference.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/testsupport/discovery/AvailableApisTestDataFactory.java
- Added funds confirmation consent in the API reference to be published in the discovery endpoint
- Delete Get funds confirmation by confirmationId, this api is not in the spec
- Added funds confirmation API entries to api test data factory
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/601
> 601: added funds confirmation as new API reference

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/AvailableApiEndpoint.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/AvailableApiEndpointsResolver.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/ControllerEndpointBlacklistHandler.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/DiscoveryApiService.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/ApplicationStartupListener.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/web/DisabledEndpointInterceptor.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/AvailableApiEndpointsResolverTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/AvailableApiEndpointsResolverVersionMatcherTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/DiscoveryApiServiceTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/discovery/DiscoveryControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/testsupport/discovery/AvailableApisTestDataFactory.java
Initialising the AvailableApiEndpoint collection and blacklisted API collection at startup, as this data does not change. This fixes the memory leak and ConcurrentModificationExceptions by only building these collections once.
Changed AvailableApiEndpoint object to store a uriPath rather than a full uri that can be used externally, which removes any dynamic data from this object enabling us to do the processing once. A fully qualified externally callable uri is then built in the DiscoveryController using the request context data i.e. X-Forwarded-Host + X-Forwarded-Path.
In order to initialise the blacklist at startup, bean dependencies needed to be adjusted which resulted in a cyclic dependency on the Spring WebMvc. This issue has been resolved by doing late binding of the …
> 1089: Fixing concurrency issues and memory leak in the Discovery API

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/ResourceStoreRepoConfiguration.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/RSServerApplication.java
Creating MongoCustomConversions bean that has the DateToUTCDateTimeConverter converter installed.
Fixing RSServerApplication to delegate Mongo related configuration to ResourceStoreRepoConfiguration.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1090
> 1090: Using custom data converter to decode Mongo Date objects as UTC

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalpayments/InternationalPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalscheduledpayments/InternationalScheduledPaymentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/internationalstandingorders/InternationalStandingOrdersApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/vrp/DomesticVrpsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/validator/OBRisk1Validator.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/validator/PaymentSubmissionValidator.java
- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBRisk1Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBDomesticVRPConsentRequestValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticConsent4Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticScheduledConsent4Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticStandingOrderConsent5Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalConsent5Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalScheduledConsent5Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalStandingOrderConsent6Validator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/OBRisk1ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBDomesticVRPConsentRequestValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticConsent4ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticScheduledConsent4ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteDomesticStandingOrderConsent5ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalConsent5ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalScheduledConsent5ValidatorTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBWriteInternationalStandingOrderConsent6ValidatorTest.java
- Creating com.forgerock.sapi.gateway.ob.uk.rs.validation.obie.payment.OBRisk1Validator impl in RS validation framework module
- Existing validation logic ported over
- Adding spring config to control payment context code validation: `rs.obie.validation.config.payments.requirePaymentContextCode` by default this is false
- Deprecating:
- Original validator: com.forgerock.sapi.gateway.ob.uk.rs.server.validator.OBRisk1Validator
- com.forgerock.sapi.gateway.ob.uk.rs.server.validator.PaymentSubmissionValidator.validateIdempotencyKeyAndRisk removing calls to it from the latest payment controllers (they will use the validation framework)
By default, the OBRisk1Validator applies no validation rules. Specific deployments can customise the behaviour by Spring config to enable paymentContextCode …
> 1086: Porting OBRisk1Validator to use the validation framework

- pom.xml
- secure-api-gateway-ob-uk-rs-backoffice-api/pom.xml
- secure-api-gateway-ob-uk-rs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/pom.xml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-validation/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-core/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
- Upgrade version to 2.0.0
- Bumped RCS store client 2.0.0
- Bumped parent version 2.0.0
- Bumped commons version 2.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
> 1099: upgrade version to 2.0.0 Blur

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- Upgrade helm chart to 2.0.1
- Bumped RS store client release 2.0.1
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1102
> 1102: prepare release 2.0.1

- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/configuration/CloudClientConfiguration.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientService.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/configuration/CloudClientConfigurationTest.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientServiceTest.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/resources/application-test.yml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/resources/application-test.yml
- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rs-server/src/test/resources/application-test.yml
CloudClientConfiguration is responsible for configuring the rcs-cloud-client module.
Renamed Spring config properties to use the cloud.client prefix
Updated helm chart to set the cloud.client.baseUri property to GATEWAY_DATA_REPO_URI from the configmap
https://github.com/SecureApiGateway/SecureApiGateway/issues/1082
> 1082: Renaming ConsentRepoConfiguration to CloudClientConfiguration

- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/file/FilePaymentsApiControllerTest.java
FilePaymentsApiControllerTest - adding tests for:
- Creating a Payment
- Idempotency
- Validation errors
- Get existing payment
https://github.com/SecureApiGateway/SecureApiGateway/issues/1074
> 1074: Adding test coverage for FilePaymentsApiControllerTest

- pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/DataEventsApi.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/DataEventsApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/FRDataEventsConverter.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/events.md
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/exceptions/DataApiExceptionHandler.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/DataEventsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/resources/application-test.yml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/events/FREventMessage.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/events/FREventMessages.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/entity/event/FREventMessageEntity.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/events/FREventMessageRepository.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/service/event/EventPollingService.java
- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/event/v3_1_2/aggregatedpolling/AggregatedPollingApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/service/event/EventPollingServiceTest.java
- Added admin data events API from the TPP can import, export, update and delete event messages
- Upgrade commons version to 2.0.2-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/998
> 998: events backoffice event notification api

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/events/DataEventsApiController.java
Defaulting rs.data.upload.limit.events property in the annotation to 10. This makes upgrading easier for extensions projects which have their own spring configuration file.
https://github.com/SecureApiGateway/SecureApiGateway/issues/998
> 998: Defaulting property rs.data.upload.limit.events in annotation

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/payment/file/processor/BasePaymentFileProcessor.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/payment/file/processor/OBIEPain001FileProcessor.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/payment/file/processor/OBIEPaymentInitiation31FileProcessor.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/payment/file/BasePaymentFileProcessorTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/common/payment/file/OBIEPaymentInitiation31FileProcessorTest.java
The FileParseException does not allow implementations enough flexibility in choosing specific error codes to return to the user. Changing processFileImpl method to throw OBErrorException so that subclasses are able to specify the errorCode.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1123
> 1123: Changing BasePaymentFileProcessor.processFileImpl to throw OBErrorException

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/validation/DefaultOBValidationModule.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBVRPFundsConfirmationRequestValidator.java
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/validation/obie/payment/consent/OBVRPFundsConfirmationRequestValidatorTest.java
- Added OBVRPFundsConfirmationRequestValidator which validates the consentId in the funds confirmation request matches the access_token and that the consent is Authorised
- Updated DomesticVrpConsentsApiController to use the new validator when processing funds confirmation requests
https://github.com/SecureApiGateway/SecureApiGateway/issues/1133
> 1133: Adding validation framework support for VRP Funds Confirmation Requests

- .github/workflows/merge.yml
Using a consolidated build step which runs the tests and produces the docker image, step: `Build Code + Test + Create Docker Image`. This prevents the tests from being run twice as we are not executing multiple make targets.
This follows the same pattern that we use in the PR build workflow, the changes for this were introduced here: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/213
https://github.com/SecureApiGateway/SecureApiGateway/issues/1076
> 1076: Cleaning up the merge GitHub action to prevent the tests being run twice

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/file/FilePaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/file/FilePaymentConsentsApiControllerTest.java
Validating that the HTTP ContentType header value for the File Payment File Upload request matches the value expected for the FileType that is specified in the Consent.
If the ContentType does not match then a HTTP 415 Unsupported Media Type response is returned.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1140
> 1140: Adding ContentType validation to File Payment File Upload Requests

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rs-backoffice-api/pom.xml
- secure-api-gateway-ob-uk-rs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rs-obie-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/pom.xml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-validation/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-core/pom.xml
- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
- Updated development version to 2.1.0-SNAPSHOT
- Bumped common version 2.1.0
- Bumped RCS api version 2.1.0
- Updated helm chart to 2.1.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1148
> 1148: prepare release 2.1.0

- pom.xml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/configuration/WebMvcConfig.java
- secure-api-gateway-ob-uk-rs-server/src/main/resources/logback.xml
- secure-api-gateway-ob-uk-rs-server/src/test/resources/logback-test.xml
Installing FapInteractionIdFilter which stores the x-fapi-interaction-id header value in the logging context (MDC).
Updating logging configuration to use a JSON log format, which automatically adds the MDC data to the log message. Logging will now be consistent with IG.
Adding logback dependencies to support JSON logging.
Example log (pretty printed):
```
{
"timestamp": "2023-10-31T16:06:14.312Z",
"level": "INFO",
"thread": "http-nio-auto-1-exec-4",
"mdc": {
"x-fapi-interaction-id": "acadff39-eca0-4d08-b33b-e549e73daf8a"
},
"logger": "com.forgerock.sapi.gateway.ob.uk.rs.server.idempotency.IdempotentRepositoryAdapter",
"message": "Created new Payment Submission: 992677bc-e8e3-490b-8883-d3e7f7fbf811",
"context": "default"
}
```
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Logging x-fapi-interaction-id header via logging context (MDC)

- pom.xml
Latest Consent Store Client API includes logic to set the x-fapi-interaction-id header in the Requests it makes to the Consent Store Server.
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Updating Consent Store Client API version

- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientService.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientServiceTest.java
Adding x-fapi-interaction-id to HTTP call made to ID Cloud API from UserClientService
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Setting x-fapi-interaction-id when calling ID Cloud API

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_9/vrp/DomesticVrpsApiController.java
The response to the PUT VRP Payment Consent request does not contain the mandatory StatusUpdateTime field.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1207
> 1207: Add StatusUpdateTime to VRP Consent response

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- secure-api-gateway-ob-uk-rs-server/docker/docker-compose-git.yml
- secure-api-gateway-ob-uk-rs-server/docker/docker-compose.yml
- secure-api-gateway-ob-uk-rs-server/pom.xml
- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202
> 987: Migration to Artifact Registry

- secure-api-gateway-ob-uk-rs-validation/secure-api-gateway-ob-uk-rs-validation-obie/pom.xml
The logback-classic dependency is included (with test scope) in order to get logging when running tests for rs-validation-obie module. This is needed because this module has no dependency on Spring, all other modules get logging configured via Spring dependencies.
Removing the explicit version number from the pom to fix and issue raised by the enforcer plugin wrt DependencyConvergence
https://github.com/SecureApiGateway/SecureApiGateway/issues/1220
> 1220: Removing version from logback-classic dependency in rs-validation-obie module

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/exceptions/GlobalExceptionHandler.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/exceptions/GlobalExceptionHandlerTest.java
Adding test for handling of missing request headers, HTTP method not supported and request media type not supported.
Cleaned up GlobalException handler to remove testing exception string error messages and instead made us of instanceof. Implemented this for MissingRequestHeaderException, removed error conditions which are not reachable.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1236
> 1236: Adding coverage for GlobalExceptionHandler

- secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml
server.max-http-header-size has been deprecated and has been replaced with server.max-http-request-header-size, updating our application config to use the new property
https://github.com/SecureApiGateway/SecureApiGateway/issues/1235
> 1235: Configure server.max-http-request-header-size

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApi.java
When the media types supported are not specified, then Spring will do content negotiation with the client and attempt to work with the most appropriate type.
Our APIs are JSON based and should be configured as such. A benefit of this change is that static analysis tools, like CodeQL, will not flag potential XSS attack as being possible on this API.
This will resolve the following security issue: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/security/code-scanning/7
https://github.com/SecureApiGateway/SecureApiGateway/issues/1258
> 1258: Specifying media types that are produced and/or consumed by the DataApi

- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientService.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientServiceTest.java
- Removing trailing '}'
- Fixing parameter name to userName
https://github.com/SecureApiGateway/SecureApiGateway/issues/1296
> 1296: Fix UserClientService query by username URI

- _infra/helm/securebanking-openbanking-uk-rs/readme.md
- _infra/helm/securebanking-openbanking-uk-rs/templates/deployment.yaml
Rename deployment-config to be core-deployment-config & ob-deployment-config
Change openig-secrets-env to core-secrets & ob-secrets
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1315
> 1315: Remove unwanted config from dev-core

- pom.xml
- Updating parent version to 2.3.2-SNAPSHOT
- Updating common to 2.3.1-SNAPSHOT
- Updating consent API to 2.3.1-SNAPSHOT
https://github.com/SecureApiGateway/SecureApiGateway/issues/1364
> 1364: Using latest versions of SAPI-G dependencies

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/accounts/accounts/FRAccountRepositoryImpl.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountsApiControllerTest.java
When both basic and detail account permissions were added the basic account detail was returned instead of the detailed account data Issue: https://github.com/ForgeCloud/secure-api-gateway-relenv-deployer/pull/42
> 1431: Fix priority of permissions for account access

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdater.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataUpdaterTest.java
The DataUpdater has been fixed to query for the FRParty object using the userId.
DataApiController has been updated to ensure that the userId field is always set. The update method is currently keyed off the username field, any value in the userId field will be overwritten to the value retrieved from the platform for the username.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1430
> 1430: Fix party not found when updating user data

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataExporter.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiControllerTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataExporterTest.java
A bug in the data export was causing the exported data for an individual user to contain data for all of the users.
The bug was due to the data paging being implemented incorrectly.
New service: DataExporter has been created which handles gathering the account data. It contains a reusable function which handles processing a paging query.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1430
> 1430: Fix User Account Data export bug

- secure-api-gateway-ob-uk-rs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientService.java
- secure-api-gateway-ob-uk-rs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/cloud/client/services/UserClientServiceTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiController.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/test/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/DataApiControllerTest.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/datamodel/user/FRUserData.java
The username was previously being set to the userId.
Setting the username correctly by querying the platform for the user data.
This now allows exported data to be re-imported without any errors, which makes the process of updating an existing user's data more straightforward.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1430
> 1430: Fix username in user data export

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-api/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/api/admin/FakeDataApiController.java
Setting:
- FRScheduledPayment.scheduledPayment.accountId
- FROffer.offer.accountId
The nested accountId fields need to be set in order to allow the data to be updated by the Data API.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1430
> 1430: Always set accountId in data created by FakeDataApiController

- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/accounts/balances/FRBalanceRepository.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/account/AccountsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/account/AccountsApiControllerTest.java
This fixes a bug in the backoffice AccountsApiController.getAccountWithBalanceByIdentifiers method which fails if the account contains multiple balances.
Both methods for getting accounts now populate the balances in the same fashion (and can handle multiple accounts).
https://github.com/SecureApiGateway/SecureApiGateway/issues/1478
> 1478: Fix backoffice accounts query to work with multiple balances

- secure-api-gateway-ob-uk-rs-backoffice-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/backoffice/api/account/AccountsApi.java
- secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/accounts/accounts/FRAccountRepository.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/account/AccountsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/backoffice/account/AccountsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountAccessConsentsApiControllerTest.java
The accountIdentifierName corresponds to the name of the user that owns the account.
When querying by account identifiers the userId, identification value and schemeName must be provided, the name is optional for some payments (all except VRP) and the existing database data in the name field is unlikely to match what is provided by the TPP.
If name validation is required for certain flows (not being implemented currently), then it can be done in the biz logic using the data returned from the database.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1479
> 1479: Remove accountIdentifierName from account queries

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/exceptions/GlobalExceptionHandler.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/account/v3_1_10/accounts/AccountAccessConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/funds/v3_1_10/FundsConfirmationConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticpayments/DomesticPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticstandingorders/DomesticStandingOrderConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/file/FilePaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalpayments/InternationalPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrderConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpConsentsApiControllerTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/exceptions/GlobalExceptionHandlerTest.java
The latest SNAPSHOT of secure-api-gateway-ob-uk-common-datamodel has moved OBStandardErrorCodes1 to pkg: uk.org.openbanking.datamodel.error.OBStandardErrorCodes1
https://github.com/SecureApiGateway/SecureApiGateway/issues/1440
> 1479: Fix import for OBStandardErrorCodes1

- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticpayments/DomesticPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticpayments/DomesticPaymentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticscheduledpayments/DomesticScheduledPaymentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticstandingorders/DomesticStandingOrderConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/domesticstandingorders/DomesticStandingOrdersApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/file/FilePaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/file/FilePaymentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalpayments/InternationalPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalpayments/InternationalPaymentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalscheduledpayments/InternationalScheduledPaymentConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalscheduledpayments/InternationalScheduledPaymentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalstandingorders/InternationalStandingOrderConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/internationalstandingorders/InternationalStandingOrdersApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/vrp/DomesticVrpConsentsApi.java
- secure-api-gateway-ob-uk-rs-obie-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/obie/api/payment/v4_0_0/vrp/DomesticVrpsApi.java
Add SAPI-G custom header x-api-client-id to the v4 controllers.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1440
> 1440: Add x-api-client-id header param to v4 payment controllers

- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBDomesticVRPConsentResponseFactory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticConsentResponse5Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticScheduledConsentResponse5Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticStandingOrderConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteFileConsentResponse4Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteFundsConfirmationResponse1Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalScheduledConsentResponse6Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalStandingOrderConsentResponse7Factory.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticpayments/DomesticPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticscheduledpayments/DomesticScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/domesticstandingorders/DomesticStandingOrderConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/file/FilePaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalpayments/InternationalPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalscheduledpayments/InternationalScheduledPaymentConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/internationalstandingorders/InternationalStandingOrderConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_10/vrp/DomesticVrpConsentsApiController.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBDomesticVRPConsentResponseFactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticConsentResponse5FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticScheduledConsentResponse5FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteDomesticStandingOrderConsentResponse6FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteFileConsentResponse4FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalConsentResponse6FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalScheduledConsentResponse6FactoryTest.java
- secure-api-gateway-ob-uk-rs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/factories/v3_1_10/OBWriteInternationalStandingOrderConsentResponse7FactoryTest.java
The existing OB response factories for payments are tied to the v3.1.10 schema, these classes can now be found in pkg: com.forgerock.sapi.gateway.ob.uk.rs.server.api.obie.payment.factories.v3_1_10
New factories will be required for v4.0.0 schemas.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1440
> 1440: Move OB response factories for payments to v3_1_10 pkg

- pom.xml
Bump Parent, Common & RCS to snapshot version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1605
> 1605: Make sure dev branches are not using latest snapshots for artifacts

- _infra/helm/securebanking-openbanking-uk-rs/Chart.yaml
- pom.xml
Bump helm to `4.0.4`
Bump common to `4.0.4`
Bump RCS to `4.0.4`
Revert parent to `4.0.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642
> 1642: Create SAPIG 4.0.4
